services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: pcb_dispatcher_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d circuit_board" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data: